import React, { useState, useEffect, useRef } from 'react';
import { 
  FileText, BookOpen, MessageSquare, User, Calendar, Home, Stethoscope, 
  CheckSquare, AlertCircle, Copy, Check, FileDown, Send, UserCheck, ShieldAlert 
} from 'lucide-react';

// Simple Markdown component to parse bold text and newlines
function SimpleMarkdown({ text }) {
  if (!text) return null;

  // Split text by lines
  const lines = text.split('\n');

  return (
    <div className="markdown-content">
      {lines.map((line, idx) => {
        // Headers
        if (line.startsWith('### ')) {
          return <h4 key={idx} style={{ marginTop: '1rem', marginBottom: '0.5rem', color: 'var(--text-primary)' }}>{parseLineContent(line.slice(4))}</h4>;
        }
        if (line.startsWith('## ')) {
          return <h3 key={idx} style={{ marginTop: '1.25rem', marginBottom: '0.5rem', color: 'var(--text-primary)' }}>{parseLineContent(line.slice(3))}</h3>;
        }
        if (line.startsWith('# ')) {
          return <h2 key={idx} style={{ marginTop: '1.5rem', marginBottom: '0.75rem', color: 'var(--text-primary)' }}>{parseLineContent(line.slice(2))}</h2>;
        }

        // Bullet lists
        if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
          return (
            <ul key={idx} style={{ margin: '0.25rem 0 0.25rem 1.25rem' }}>
              <li>{parseLineContent(line.trim().slice(2))}</li>
            </ul>
          );
        }

        // Numbered lists
        const numMatch = line.trim().match(/^(\d+)\.\s(.*)/);
        if (numMatch) {
          return (
            <ol key={idx} start={numMatch[1]} style={{ margin: '0.25rem 0 0.25rem 1.25rem' }}>
              <li>{parseLineContent(numMatch[2])}</li>
            </ol>
          );
        }

        // Standard paragraph
        if (line.trim() === '') return <div key={idx} style={{ height: '0.5rem' }} />;
        return <p key={idx}>{parseLineContent(line)}</p>;
      })}
    </div>
  );
}

// Helper to parse line bold tags **bold**
function parseLineContent(text) {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part, index) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={index} style={{ color: 'var(--text-primary)', fontWeight: '600' }}>{part.slice(2, -2)}</strong>;
    }
    return part;
  });
}

export default function InsightsPanel({ reportData, chatSession, isAnalyzing }) {
  const [activeTab, setActiveTab] = useState('summary');
  const [copied, setCopied] = useState(false);
  const [chatMessages, setChatMessages] = useState([]);
  const [userInput, setUserInput] = useState('');
  const [isChatLoading, setIsChatLoading] = useState(false);
  
  const chatBottomRef = useRef(null);

  // Initialize chat messages when chatSession or reportData changes
  useEffect(() => {
    if (chatSession) {
      // Re-fetch history if any exists in the session, or start with default
      setChatMessages([
        { 
          role: 'assistant', 
          text: "I have successfully analyzed the medical document. I'm ready to answer any questions you have about these results! What would you like to clarify?" 
        }
      ]);
    } else {
      setChatMessages([]);
    }
  }, [chatSession, reportData]);

  // Scroll to bottom of chat when messages change
  useEffect(() => {
    if (chatBottomRef.current) {
      chatBottomRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [chatMessages, isChatLoading, activeTab]);

  if (isAnalyzing) {
    return (
      <div className="insights-panel" style={{ padding: '2rem' }}>
        <h3 style={{ marginBottom: '1.5rem' }}>Processing Document Analysis...</h3>
        <div className="skeleton-loader">
          <div className="skeleton-line title"></div>
          <div className="skeleton-line long"></div>
          <div className="skeleton-line medium"></div>
          <div className="skeleton-line long"></div>
          <div className="skeleton-line short"></div>
          <div style={{ height: '1rem' }}></div>
          <div className="skeleton-line title"></div>
          <div className="skeleton-line long"></div>
          <div className="skeleton-line long"></div>
          <div className="skeleton-line medium"></div>
        </div>
      </div>
    );
  }

  if (!reportData) {
    return (
      <div className="insights-panel" style={{ padding: '2rem', justifyContent: 'center', alignItems: 'center', color: 'var(--text-muted)' }}>
        <p>No document active. Upload a medical document to get started.</p>
      </div>
    );
  }

  const { metadata, chiefComplaint, summary, findings, recommendations, dictionary } = reportData;

  const handleCopySummary = () => {
    const textToCopy = `
MEDICAL REPORT SUMMARY (Generated by AegisScan AI)
--------------------------------------------------
Document Type: ${metadata.documentType || 'N/A'}
Patient Name: ${metadata.patientName || 'N/A'}
Date: ${metadata.documentDate || 'N/A'}
Facility: ${metadata.facilityName || 'N/A'}

Chief Complaint:
${chiefComplaint || 'N/A'}

Key Findings:
${findings?.map(f => `- ${f}`).join('\n') || 'None'}

Recommendations:
${recommendations?.map(r => `- ${r}`).join('\n') || 'None'}

Detailed Summary:
${summary || 'N/A'}

Disclaimer:
Always consult with a qualified physician or healthcare provider regarding any medical concern, diagnostic reading, or treatment decisions.
    `.trim();

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    const textToCopy = `
MEDICAL REPORT SUMMARY (Generated by AegisScan AI)
--------------------------------------------------
Document Type: ${metadata.documentType || 'N/A'}
Patient Name: ${metadata.patientName || 'N/A'}
Date: ${metadata.documentDate || 'N/A'}
Facility: ${metadata.facilityName || 'N/A'}

Chief Complaint:
${chiefComplaint || 'N/A'}

Key Findings:
${findings?.map(f => `- ${f}`).join('\n') || 'None'}

Recommendations:
${recommendations?.map(r => `- ${r}`).join('\n') || 'None'}

Detailed Summary:
${summary || 'N/A'}
    `.trim();

    const element = document.createElement("a");
    const file = new Blob([textToCopy], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `AegisScan_Summary_${(metadata.patientName || "Report").replace(/\s+/g, "_")}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleSendMessage = async (textToSend) => {
    const messageText = textToSend || userInput;
    if (!messageText.trim() || !chatSession || isChatLoading) return;

    // Add user message to UI
    setChatMessages(prev => [...prev, { role: 'user', text: messageText }]);
    if (!textToSend) setUserInput('');
    setIsChatLoading(true);

    try {
      const response = await chatSession.sendMessage(messageText);
      const replyText = response.response.text();
      setChatMessages(prev => [...prev, { role: 'assistant', text: replyText }]);
    } catch (err) {
      console.error("Chat error:", err);
      setChatMessages(prev => [...prev, { role: 'assistant', text: "Error communicating with AI. Please make sure your API key is correct and valid." }]);
    } finally {
      setIsChatLoading(false);
    }
  };

  const suggestions = [
    "Explain my results in simpler terms",
    "Are there any life-threatening issues here?",
    "What follow-up appointments are recommended?",
    "What do my lab values mean?"
  ];

  return (
    <div className="insights-panel">
      {/* Navigation tabs */}
      <div className="insights-header-tabs" role="tablist">
        <button 
          className={`tab-btn ${activeTab === 'summary' ? 'active' : ''}`}
          onClick={() => setActiveTab('summary')}
          role="tab"
          aria-selected={activeTab === 'summary'}
        >
          <FileText size={16} />
          Summary
        </button>
        <button 
          className={`tab-btn ${activeTab === 'dictionary' ? 'active' : ''}`}
          onClick={() => setActiveTab('dictionary')}
          role="tab"
          aria-selected={activeTab === 'dictionary'}
        >
          <BookOpen size={16} />
          Medical Terms ({dictionary?.length || 0})
        </button>
        <button 
          className={`tab-btn ${activeTab === 'chat' ? 'active' : ''}`}
          onClick={() => setActiveTab('chat')}
          role="tab"
          aria-selected={activeTab === 'chat'}
        >
          <MessageSquare size={16} />
          Consult AI Chat
        </button>
      </div>

      {/* Insights Content Body */}
      <div className="insights-body">
        {activeTab === 'summary' && (
          <div className="summary-container">
            {/* Metadata Badges */}
            <div className="summary-card">
              <div className="summary-card-header patient">
                <User size={16} />
                <span>Patient & Document Details</span>
              </div>
              <div className="patient-grid">
                <div className="patient-data-item">
                  <span className="patient-label">Patient Name</span>
                  <span className="patient-value">{metadata.patientName}</span>
                </div>
                <div className="patient-data-item">
                  <span className="patient-label">Age / Gender</span>
                  <span className="patient-value">{metadata.patientAge} / {metadata.patientGender}</span>
                </div>
                <div className="patient-data-item">
                  <span className="patient-label">Doc Date</span>
                  <span className="patient-value">{metadata.documentDate}</span>
                </div>
                <div className="patient-data-item">
                  <span className="patient-label">Report Type</span>
                  <span className="patient-value" style={{ color: 'var(--color-primary)' }}>{metadata.documentType}</span>
                </div>
                <div className="patient-data-item" style={{ gridColumn: 'span 2' }}>
                  <span className="patient-label">Facility</span>
                  <span className="patient-value">{metadata.facilityName}</span>
                </div>
              </div>
            </div>

            {/* Chief Complaint */}
            {chiefComplaint && (
              <div className="summary-card">
                <div className="summary-card-header" style={{ color: 'var(--color-primary)' }}>
                  <Stethoscope size={16} />
                  <span>Clinical Indication / Reason</span>
                </div>
                <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>{chiefComplaint}</p>
              </div>
            )}

            {/* Bullet Findings */}
            {findings && findings.length > 0 && (
              <div className="summary-card">
                <div className="summary-card-header findings">
                  <AlertCircle size={16} />
                  <span>Key Findings Summary</span>
                </div>
                <ul style={{ paddingLeft: '1.25rem', color: 'var(--text-secondary)', fontSize: '0.9rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                  {findings.map((finding, i) => (
                    <li key={i}>{parseLineContent(finding)}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Action Items */}
            {recommendations && recommendations.length > 0 && (
              <div className="summary-card">
                <div className="summary-card-header actions">
                  <CheckSquare size={16} />
                  <span>Recommendations & Next Steps</span>
                </div>
                <ul style={{ paddingLeft: '1.25rem', color: 'var(--text-secondary)', fontSize: '0.9rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                  {recommendations.map((recommendation, i) => (
                    <li key={i}>{parseLineContent(recommendation)}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Detailed Summarized Paragraphs */}
            <div className="summary-card">
              <div className="summary-card-header" style={{ color: 'var(--color-accent)' }}>
                <FileText size={16} />
                <span>Clinical Overview</span>
              </div>
              <SimpleMarkdown text={summary} />
            </div>

            {/* Export and Action Buttons */}
            <div className="summary-export-bar">
              <button className="export-btn" onClick={handleCopySummary} aria-label="Copy summary to clipboard">
                {copied ? <Check size={15} style={{ color: 'var(--color-success)' }} /> : <Copy size={15} />}
                <span>{copied ? 'Copied!' : 'Copy Summary'}</span>
              </button>
              <button className="export-btn primary" onClick={handleDownloadTxt} aria-label="Download summary as TXT">
                <FileDown size={15} />
                <span>Download Report</span>
              </button>
            </div>

            {/* Medical Disclaimer */}
            <div className="summary-card" style={{ background: 'rgba(244, 63, 94, 0.02)', borderColor: 'rgba(244, 63, 94, 0.15)' }}>
              <div className="summary-card-header disclaimer" style={{ color: 'var(--color-danger)' }}>
                <ShieldAlert size={16} />
                <span>Patient Health Disclaimer</span>
              </div>
              <p className="disclaimer-text">
                AegisScan AI is an automated machine learning tool designed to facilitate document review and clinical concept education. This translation does NOT constitute official medical advice, diagnosis, treatment, or clinical opinion. Patients should review all medical documentation and clinical summaries directly with their primary care provider or specialist physician. Do not delay seeking medical consultation due to information provided here.
              </p>
            </div>
          </div>
        )}

        {activeTab === 'dictionary' && (
          <div className="dictionary-grid">
            <h4 style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '0.5rem', fontWeight: '500' }}>
              The AI identified the following complex medical terms in your scan and defined them in plain terms:
            </h4>
            
            {dictionary && dictionary.length > 0 ? (
              dictionary.map((item, i) => (
                <div key={i} className="dict-item-card">
                  <div className="dict-term-header">
                    <span className="dict-term-title">{item.term}</span>
                    {item.pronunciation && (
                      <span className="dict-term-pronounce">/{item.pronunciation}/</span>
                    )}
                  </div>
                  <p className="dict-term-definition">{item.definition}</p>
                  {item.context && (
                    <p className="dict-term-context">
                      <strong>In your document:</strong> "{item.context}"
                    </p>
                  )}
                </div>
              ))
            ) : (
              <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-muted)' }}>
                No complex medical terminology extracted from this scan.
              </div>
            )}
          </div>
        )}

        {activeTab === 'chat' && (
          <div className="chat-container">
            {/* Conversation Log */}
            <div className="chat-history">
              {chatMessages.map((msg, index) => (
                <div key={index} className={`chat-message ${msg.role === 'user' ? 'user' : 'assistant'}`}>
                  <span className="chat-sender">
                    {msg.role === 'user' ? 'You' : 'AegisScan Assistant'}
                  </span>
                  <div className="chat-bubble">
                    <SimpleMarkdown text={msg.text} />
                  </div>
                </div>
              ))}
              
              {isChatLoading && (
                <div className="chat-message assistant">
                  <span className="chat-sender">AegisScan Assistant</span>
                  <div className="chat-bubble" style={{ padding: '0.75rem 1rem' }}>
                    <div style={{ display: 'flex', gap: '4px', alignItems: 'center', height: '14px' }}>
                      <div className="status-dot active" style={{ animation: 'pulse-slow 1s infinite', width: '6px', height: '6px' }}></div>
                      <div className="status-dot active" style={{ animation: 'pulse-slow 1s infinite 0.2s', width: '6px', height: '6px' }}></div>
                      <div className="status-dot active" style={{ animation: 'pulse-slow 1s infinite 0.4s', width: '6px', height: '6px' }}></div>
                    </div>
                  </div>
                </div>
              )}
              <div ref={chatBottomRef} />
            </div>

            {/* Quick Suggestion Chips */}
            <div className="chat-suggestions">
              {suggestions.map((s, idx) => (
                <button
                  key={idx}
                  className="suggest-btn"
                  onClick={() => handleSendMessage(s)}
                  disabled={isChatLoading || !chatSession}
                >
                  {s}
                </button>
              ))}
            </div>

            {/* Input Form */}
            <form 
              className="chat-input-wrapper"
              onSubmit={(e) => {
                e.preventDefault();
                handleSendMessage();
              }}
            >
              <input
                type="text"
                className="chat-input"
                placeholder="Ask a question about this medical document..."
                value={userInput}
                onChange={(e) => setUserInput(e.target.value)}
                disabled={isChatLoading || !chatSession}
              />
              <button
                type="submit"
                className="chat-send-btn"
                disabled={isChatLoading || !userInput.trim() || !chatSession}
                aria-label="Send message"
              >
                <Send size={16} />
              </button>
            </form>
          </div>
        )}
      </div>
    </div>
  );
}
